
modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
[[mods]]
modId="sakura"
version="${file.jarVersion}"
displayName="Sakura Mod" 
displayURL="https://www.curseforge.com/minecraft/mc-mods/sakura" 
logoFile="logo.png"
credits="MCMOD Modding Group, MMF-Group"
authors="Syameimaru Zheng, Bagu_chan"
description='''
A mod that mix Bamboo, WA and MapleTree.

This mod is full of Japanese style, Teishoku, sushi, and lots of foods.
New battle styles with your katana and kodachi, Cooking with campfire and cooking pot.
New illager with his katana spawn in Bamboo forest and maple forest!
New dress: Kimono, yukata and Haori.
'''
[[dependencies.sakura]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sakura]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sakura]]
    modId="mmlib"
    mandatory=true
    versionRange="[1.1.1-1.18.2,)"
    ordering="AFTER"
    side="BOTH"